.ORIG x0100
TRAP_GETC 
    TRAP xff
    INF_LOOP_GETC BR INF_LOOP_GETC
TRAP_OUT
    TRAP xff
    INF_LOOP_OUT BR INF_LOOP_OUT
TRAP_PUTS
    TRAP xff
    INF_LOOP_PUTS BR INF_LOOP_PUTS
TRAP_IN
    TRAP xff
    INF_LOOP_IN BR INF_LOOP_IN
TRAP_PUTSP
    TRAP xff
    INF_LOOP_PUTSP BR INF_LOOP_PUTSP
TRAP_HALT
    ;;INF_LOOP_HALT BR INF_LOOP_HALT
    BR TO_PROCESS1

TRAP_YIELD
    BR YIELD1

YIELD1
    LDI R6, STATUS_PROCESS1
    ADD R6, R6, #-1
    BRp YIELD1_CHANGE
    BRnz YIELD2
YIELD1_CHANGE
    LD R2, READY
    STI R2, STATUS_PROCESS1
    ADD R1, R1, #2
    ;;TRAP xff
    BR TO_PROCESS2
YIELD2
    LDI R6, STATUS_PROCESS2
    ADD R6, R6, #-1
    BRp YIELD2_CHANGE
    BRnz YIELD3
YIELD2_CHANGE
    LD R2, READY
    STI R2, STATUS_PROCESS2
    ADD R1, R1, #2
    ;;TRAP xff
    BR TO_PROCESS3
YIELD3
    LDI R6, STATUS_PROCESS3
    ADD R6, R6, #-1
    BRp YIELD3_CHANGE
    BRnz YIELD4
YIELD3_CHANGE
    LD R2, READY
    STI R2, STATUS_PROCESS3
    ADD R1, R1, #2
    ;;TRAP xff
    BR TO_PROCESS4
YIELD4
    LDI R6, STATUS_PROCESS4
    ADD R6, R6, #-1
    BRp YIELD4_CHANGE
    BRnz YIELD5
YIELD4_CHANGE
    LD R2, READY
    STI R2, STATUS_PROCESS4
    ADD R1, R1, #2
    ;;TRAP xff
    BR TO_PROCESS5
YIELD5
    LDI R6, STATUS_PROCESS5
    ADD R6, R6, #-1
    BRp YIELD5_CHANGE
    BRnz YIELD1
YIELD5_CHANGE
    LD R2, READY
    STI R2, STATUS_PROCESS5
    ADD R1, R1, #2
    ;;TRAP xff
    BR TO_PROCESS1

TO_PROCESS1
    LDI R6, STATUS_PROCESS1
    ADD R6, R6, #-1

    ;; START P1 (2)
    ;;TRAP xff

    BRz PROCESS1_RUN
    BRp PROCESS1_END
    BRn TO_PROCESS2

PROCESS1_RUN
    LD R2, RUNNING
    STI R2, STATUS_PROCESS1
    LD R5, PROCESS1
    JMP R5

PROCESS1_END
    LD R2, FINISH
    STI R2, STATUS_PROCESS1

    ;; END P1 (3)
    ;;TRAP xff

TO_PROCESS2
    LDI R6, STATUS_PROCESS2
    ADD R6, R6, #-1

    ;; START P2 (4)
    ;;TRAP xff

    BRz PROCESS2_RUN
    BRp PROCESS2_END
    BRn TO_PROCESS3

PROCESS2_RUN
    LD R2, RUNNING
    STI R2, STATUS_PROCESS2
    LD R5, PROCESS2
    JMP R5

PROCESS2_END
    LD R2, FINISH
    STI R2, STATUS_PROCESS2

    ;; END P2 (5)
    ;;TRAP xff

TO_PROCESS3
    LDI R6, STATUS_PROCESS3
    ADD R6, R6, #-1

    ;; START P3 (6)
    ;;TRAP xff

    BRz PROCESS3_RUN
    BRp PROCESS3_END
    BRn TO_PROCESS4

PROCESS3_RUN
    LD R2, RUNNING
    STI R2, STATUS_PROCESS3
    LD R5, PROCESS3
    JMP R5

PROCESS3_END
    LD R2, FINISH
    STI R2, STATUS_PROCESS3

    ;; END P3 (7)
    ;;TRAP xff

TO_PROCESS4
    LDI R6, STATUS_PROCESS4
    ADD R6, R6, #-1

    ;; START P4 (8)
    ;;TRAP xff

    BRz PROCESS4_RUN
    BRp PROCESS4_END
    BRn TO_PROCESS5

PROCESS4_RUN
    LD R2, RUNNING
    STI R2, STATUS_PROCESS4
    LD R5, PROCESS4
    JMP R5

PROCESS4_END
    LD R2, FINISH
    STI R2, STATUS_PROCESS4

    ;; END P4 (9)
    ;;TRAP xff

TO_PROCESS5
    LDI R6, STATUS_PROCESS5
    ADD R6, R6, #-1

    ;; START P5 (10)
    ;;TRAP xff

    BRz PROCESS5_RUN
    BRp PROCESS5_END
    BRn TO_PROCESSEND

PROCESS5_RUN
    LD R2, RUNNING
    STI R2, STATUS_PROCESS5
    LD R5, PROCESS5
    JMP R5

PROCESS5_END
    LD R2, FINISH
    STI R2, STATUS_PROCESS5

    ;; END P5 (11)
    ;;TRAP xff

TO_PROCESSEND

    ;; START INF (12)
    ;;TRAP xff

    INF_LOOP_PROCESS BR INF_LOOP_PROCESS


READY .FILL #1
FINISH .FILL #0
RUNNING .FILL #2
PROCESS1 .FILL x4000
PROCESS2 .FILL x5000
PROCESS3 .FILL x6000
PROCESS4 .FILL x7000
PROCESS5 .FILL x8000
STATUS_PROCESS1 .FILL x0200
STATUS_PROCESS2 .FILL x0201
STATUS_PROCESS3 .FILL x0202
STATUS_PROCESS4 .FILL x0203
STATUS_PROCESS5 .FILL x0204
.END